version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      # Minimal “test” just to show a step; students can expand later.
      - python -c "import flask; print('Tests passed')"
  build:
    commands:
      # Create a zip that Elastic Beanstalk can deploy
      - mkdir -p build
      - zip -r build/app.zip application.py requirements.txt
artifacts:
  files:
    - build/app.zip
  discard-paths: yes
